### ISSUE TITLE
Create a Highland Stream directly from an ES6 Iterator/Generator

### ISSUE THREAD

**Issue by voodoohop** [caolan/highland#131]
this works as a workaround. wouldn't it make sense to include more direct integration with ES6 into the library?

```javascript
_(function (push, next) {
    var e = es6Generator.next();
    if (!e.done) {
      push(null, e.value);
      next();
    }
})
```

**Comment by vqvu** [comment]
I could see us supporting iterators instead. See the code in #233. Also, the [iterator protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#The_.22iterator.22_protocol).

This will handle everything, and we don't have to detect iterables.

**Comment by svozza** [comment]
I definitely think we should support anything implementing the iterator protocol, especially now that maps and sets are available in Node v0.12 without the harmony flag. Something to think about though is how do we test these? There are [ES6 collection shims] (https://github.com/WebReflection/es6-collections) available so that would be one way but would it make more sense to have a separate set of tests specifically for Node v0.12/ES6 features?

**Comment by vqvu** [comment]
Until we're in a situation where we are supporting un-shimmable features, I think using the shims would be the easiest thing to do. Plus, I could see people using the iterator shims with 0.10, for instance, so we might as well test with it.

Unless you're worried about the shims having different semantics than the Node/V8 implementation. But that would be a bug in either Node or the shim (or both), right?

**Comment by svozza** [comment]
Yeah, I'm worried if there's a difference between the shims and Node that means our tests pass even though the feature doesn't work in Node. My thinking was that shims are always a gamble so it's not really our problem if they're 'broken' but we should absolutely make sure that we support the versions in Node v0.12 because they are now officially part of the framework. I guess the same goes for versions of Firefox and Chrome that support these features out of the box. That said, the Iterator protocol for iterables is pretty simple it's unlikely that situation would arise.

As for unshimmable features, I guess generators could fall into that bracket because I've only seen workarounds that require transpilation to get them working in ES5 environments. Of course, they just return an Iterator so theoretically once we support iterators we get generators for free but I think it might be a bit much to advertise that feature without actually having tests ran against genuine generators: there's a lot more scope for mistakes there.

**Comment by vqvu** [comment]
Fair enough. I guess my point was that we support the iterator protocol,
and that thing is so simple you don't even need a shim. Anyone can roll
their own, so we'd need to test it in our normal tests anyway. The support
for generators is only tangential, because generators happen to return an
iterator.

That said, I'm not all that opposed to a separate test with real generators
just in case. I've never fiddled much with Travis CI. How easy is it to
make it run these tests correctly?

**Comment by svozza** [comment]
Don't know much about Travis myself but I had a bit of a dig around and it looks like it's relative easily. We can create a new test script for the ES6 features and reference it in `package.json`:

```javascript
"scripts": {
    "test": "nodeunit test/test.js",
    "es6test": "nodeunit test/es6test.js"
  },
```

After that make a change to .travis.yml to run the script only if the node version is v0.12:

```bash
script:
- '[ ${TRAVIS_NODE_VERSION}" != "0.12" ] && npm test'
- '[ ${TRAVIS_NODE_VERSION}" == "0.12" ] && npm test && npm run-script es6tests'
```
To test generators it's a bit more complicated because we'd have to run with the harmony flag so package.json would have to look like this:

```javascript
"scripts": {
    "test": "nodeunit test/test.js",
    "es6test": "node --harmony `which nodeunit` lib/app.js"
  },
```
Tbh, I don't think we should officially support functionality that requires the --harmony flag, we can leave it to the discretion of users if they want to risk it.

Obviously the Travis part of this is untested, I'll only know for certain after running my PR against the build.

**Comment by vqvu** [comment]
Agreed about the `--harmony` flag. I thought you were concerned about generators, but I guess the part that we differed on was whether to use the real `Map` from node 0.12 in our tests instead of a shim. I was expecting to just make our own iterators instead of using any of the new collections objects, since separate tests are a maintenance overhead.

Actually, why not just do feature detection in our current tests? Check for the `Set` and `Symbol`objects and run the test if they exist. Remove the check if we drop support for older versions of node. That way, things will just work if we decide to start testing against iojs as well.

Checking for node version feels a lot like user-agent sniffing...

**Comment by svozza** [comment]
Yep, very good point, feature detection sounds like a nice solution, I'll do it that way.
