### ISSUE TITLE
Implement xor function

### ISSUE THREAD

**Issue by svozza** [caolan/highland#183]
I had a use case where I needed to get the elements from two streams that weren't contained in both. This is what I came up with:

```javascript
Stream.prototype.xor = function (ys) {
    return this.uniq().collect()
        .flatMap(function (array) {
            return _(ys).uniq().reduce(array, function (memo, value) {
                var i = array.indexOf(value);
                if (i > -1) {
                    memo.splice(i, 1);
                }
                else {
                    memo.push(value);
                }
                return memo;
            }).sequence();
        });
};

_.xor([1, 5, 3, 2, 7])([1, 2, 3, 9, 1]).toArray(console.log);
//=> [ 9, 5, 7 ]

```

That was fine for what I was doing but there are a few problems, for example the use of uniq, which could cause problems with large streams (mine were never more than 50 items in length), the call to splice from inside reduce and the hardcoding of strict equality due to indexOf. I can already think of ways to make this more performant and flexible but before I do any more work on it I just want to know if anyone would find this new functionality useful?

**Comment by quarterto** [comment]
I'm -1 on a kitchen sink API but maybe that horse has already bolted. I think there's a place for a separate library of stream combinators that can work with `flatMap`/`fold`, so this would be called as something like `xs.flatMap(xor(ys))`.

**Comment by jeromew** [comment]
@quarterto by 'kitchen sink api' you mean that there are already too many primitives that do too many things already (english is not my native language) or does it mean something else ?

I agree we need to solve the 'components' issue so that a library ecosystem could emerge.

so @svozza that would mean that given the rare use of `xor` (and at least until other people request it) xor should probably be written as an external module.

Now on what is the best practice for such external modules I don't think I have seen a definitive agreement on this in the related issues. This should probably be the next big subject after 3.x is out.

**Comment by quarterto** [comment]
@jeromew pretty much, yeah.

**Comment by svozza** [comment]
I like the idea of a separate library of stream combinators but yeah, there'd have to be some thought into best practices etc for extension libraries like that.

**Comment by svozza** [comment]
I'm going to close this, discussion about external modules etc makes more sense in a 3.0 thread.

**Comment by quarterto** [comment]
There's already discussion happening in #3, #70 and #148.
