### ISSUE TITLE
_.pick Returns Keys Not Present And Assigns 'undefined' To Them

### ISSUE THREAD

**Issue by svozza** [caolan/highland#195]
Not sure if this is expected behaviour or not (the test indicate it is) but if you use _.pick on a stream of objects and one of the keys you're looking for isn't present, the key still appears in the filtered stream but with the value `undefined` instead. For example,

```javascript
_([{ name: 'Test', id: 1234 }]).pick(['name', 'blah']).toArray(console.log)
// => [{ id: 1234, blah: undefined }]
```

I would have expected this output:

```javascript
// => [{ id: 1234}]
```

It also has the strange side effect where if none of the keys you are looking for are found then the objects returned are not empty like with lodash or Ramda:

```javascript
var R = require('ramda')
R.pick(['blah'], { name: 'Test', id: 1234})
// => {}
```
This makes it harder to filter out unwanted elements because you can't do something like this:

```javascript
_([{ name: 'Test', id: 1234 }, {name: 'Test'}]).pick(['id']).filter(R.isEmpty).toArray(console.log)
```
I have a pull request done for this and ready to submit if no one has any objections. Even if we don't change it, we should at least document the behaviour because it's a bit unusual.

**Comment by vqvu** [comment]
I think this is "expected behavior" in the sense that it was the easiest way to implement it rather than that it *must* be this way. @mpj originally implemented this though, so he could give a more definitive answer.

As for me, I'm happy to accept a PR that changes the behavior of `pick` to be more in-line with existing libraries.

**Comment by jeromew** [comment]
Hello,
I was the one originally asking @mpj to make the `undefined` appear.

I must admit that I did not look at what the other libraries are doing, but the way I see pick is that you want to "standardize" the downstream objects.

another way would be to push errors when pick is trying to pick a property that does not exist upstream. should the user be warned about picking a property that does not exist ?

I understand the use case with `filter` but this could be done with a specific filter and I am not sure that the `pick` handling should be drived by this use case.

what do you think ?

**Comment by svozza** [comment]
Standardising an object by filling it full of `undefined`s seems a bit strange to me but I can see the logic. 

For me, the principle of least astonishment applies and that's why I think the filter case is quite pertinent here: most queries you run in any context return an empty set if the items requested are not found, I think we should do like likewise.

That said, I do like the idea of pushing errors if certain properties don't exist and also we have to think that this could be a breaking change if people are relying on this behaviour.

**Comment by vqvu** [comment]
Thing is, there's no point in "standardizing" the downstream objects, since if you ask for an undefined key, you get `undefined` anyway (`{}['a'] // => undefined`). I don't see a real semantic difference between the two. In my experience, it's rare for people to use `hasOwnProperty` or something similar.

I agree with @svozza here about the principle of least astonishment. To me, the word "pick" implies that the result object will be a "sub-object" of the original. You're picking out the keys from the original. So it seems weird to me that it would contain keys that the original doesn't.

Another concern is that compatibility (as much as possible) with other libraries that provide the same transforms is important to help people migrate, and we shouldn't do something different unless there's a good reason.

Pushing errors may be a good solution, but we'd have to consider whether or not that would be useful to users or not before breaking back-compat.

**Comment by jeromew** [comment]
ok I went back to the original discussion on this - https://github.com/caolan/highland/pull/135#issuecomment-64048685

It seems the current behavior is more a clarification of what the PR was already doing.

it is fine with me (and probably better for migrations as you said) if pick has a behavior similar to other libs.

This seems sufficiently light (and annoying for @svozza who might be the first user of the feature except @mpj) that we consider that it is not a back-compat issue.

regarding the error handling it might be a bit more of a breaking change if we start pushing error for each missing key so I don't think it is needed now - even if for me "picking" a non existing property is definitely something that should trigger a warning.

that might be done by another transform like `checkProperty`

**Comment by svozza** [comment]
Yeah, definitely hold off on the errors part for now, it's a big enough change. Whilst we're on the subject of pick, do we want a pickBy method? It would accept a predicate function - called on each key/value pair of the object - that takes a key and value as parameters and allows the pair through if the function returns true. I may need this functionality in the future so I'd be happy to do it; it should be fairly easy to implement.

**Comment by vqvu** [comment]
`pickBy` sounds reasonable if you have a use-case for it.

**Comment by svozza** [comment]
Yeah, I actually have two: one is where you want to pick objects based on a pattern in their key like beginning with an underscore and the other is where you have a nested object and you want to pick a key on basis of a something present in the nested object.

**Comment by vqvu** [comment]
I think `_.pickBy(function)` the properties list is largely redundant with an arbitrary selector function.

**Comment by vqvu** [comment]
@svozza Please open a new issue if you want to discuss `pickBy` further. Otherwise, feel free to make a PR!
