### ISSUE TITLE
Generator + Resume = infinite loop 

### ISSUE THREAD

**Issue by ibash** [caolan/highland#207]
Code:
```javascript
var _ = require('highland');

var stream = _(function(push, next) {
  push(null, _.nil);
  next();
});

stream.resume();
// above leads to infinite loop
```

1. Is this behaving as expected?
2. If it is, should the behavior change s.t. the generator is not called again if nil is passed. Presumably downstream streams assume nothing else in coming after nil, so there's no point in calling the generator again.

**Comment by ibash** [comment]
@vqvu

**Comment by LewisJEllis** [comment]
Right now, I would call this expected behavior, but based on recent discussions on stream termination, I don't see any reason to call the generator again after it passes nil and would agree with the suggested change.

I think thus far it's been left to anyone implementing a generator to maintain this invariant, kind of like how there's a 'standard boilerplate' to implementing a custom `.consume`. Consume, however, won't fall into this sort of loop.

**Comment by vqvu** [comment]
Yes, this is expected. You're not supposed to call `next` after a `nil`. It's one invariant that the code counts on.

Agreed that it's not useful behavior though. Note that this doesn't happen on the 3.0.0 branch.

**Comment by vqvu** [comment]
Also, in my view, calling `next` or `push` after `nil` corresponds to "undefined behavior", so you really should just maintain that invariant. This is true for both `consume` and generator functions. I wouldn't depend on a certain behavior always happening.

**Comment by ibash** [comment]
Would you be a opposed to a PR that changes this? I understand it's as designed, but IMO it would lead to more consistency / less unexpected cases for users.

**Comment by quarterto** [comment]
Perhaps calling `next`/`push` after `nil` should throw? Principle of least surprise and all that.
