### ISSUE TITLE
Browser Support/Compatibility

### ISSUE THREAD

**Issue by hydrotik** [caolan/highland#238]
Not an issue (unless you consider requesting this in the README:), but I wasn't sure where to post this?I'm curious about the browser support/backwards compatibility with highland and also maybe some roadmap information?

**Comment by quarterto** [comment]
Browser support: hopefully IE8+, but since Testling is currently broken (substack/testling#88) we have no real way of checking this at the moment.

A brief roadmap:

 * 3.0: overhaul of streaming engine, fixing redirection
 * probably 3.1: ability to extend Highland streams with custom functionality
 * possibly 3.2: compatibility with Fantasy Land, _.nil back-propagation

**Comment by vqvu** [comment]
For now, there is a `grunt browserify:test-browser` task that will browserify the tests so that you can manually run them in a browser. The contributions.md has more instructions.

I've only ever run these tests in the latest Firefox, though.

**Comment by hydrotik** [comment]
Thanks all! This is very helpful. Hopefully the testing issue is resolved.
