### ISSUE TITLE
Stream.onEnd callback?

### ISSUE THREAD

**Issue by ccorcos** [caolan/highland#254]
Is there any way I can get a callback when a stream is ended?

http://stackoverflow.com/questions/29269171/integrating-meteor-with-highland-js

**Comment by vqvu** [comment]
Related to #172 and #161.

The correct solution is the API suggested in #172. Just bind to `onDestroy`, but that requires a non-backcompat change.

For now, you can do an almost equivalent. Here, `done` is the `done` proposed in #161.

```javascript
stream = _()
c = Tracker.autorun ->
  results = Posts.find().fetch()
  stream.write(results)

stream.observe().done ->
  c.stop()
```

The observe is so that you don't cause `stream` to resume immediately, since that's probably not what you want.

**Comment by ccorcos** [comment]
Ok. so just to make sure. I'm looking at the [source](https://github.com/caolan/highland/blob/master/dist/highland.js#L1292) and it seems odd that they aren't using push and next as specified in the API. Anyways, here's my go at it.

```js
done = function (f, source) {
    return source.consume(function (err, x, push, next) {
        if (err) {
            source.push(err)
            next()
        }
        else if (x === _.nil) {
            f()
            source.push(null, x)
        } else {
            next()
        }
    }).resume();
};
```

Does that look right?

How do I mixin this function with the API?

**Comment by vqvu** [comment]
You don't *have* to call `push`. Only `next` when you want the next element. Not calling `push` is a way to filter out data. There's no reason to call `push` if there is no downstream; all it does is buffer unnecessarily.

`source.push` is not a valid function, so that won't work.

There is no way to mixin new functions to the API, and there is no plan allow this. If you need the function now, I would copy the `done` function from [here](https://github.com/caolan/highland/pull/161/files), except with the `function (f, source)` signature (replace uses of `this` and `self` with `source`), then curry it and use it with `through`. `through` is currently the best way to use new transforms.

```javascript
var done = _.curry(function (f, source) {
...
});

stream.through(done(function () {
// Close resources.
}));
```

**Comment by ccorcos** [comment]
Actually now that you say that, it makes more sense to me if done is simply transparent, passing on the stream and calling that function when it ends. This way you keep chaining after it...

```js
done = _.curry(function (f, source) {
    return source.consume(function (err, x, push, next) {
        if (err) {
            push(err)
            next()
        }
        else if (x === _.nil) {
            f()
            push(null, x)
        } else {
            push(null, x)
            next()
        }
    }).resume();
});
```

**Comment by vqvu** [comment]
Yep. You're right. The `done` function as implemented in that PR is meant to be a terminal transform.

Since you want more of an `onDone` callback, it makes sense to transparently pass through everything. Just make sure you don't call `resume`. Then you can keep chaining it like normal without needing to do the `observe` I talked about before.

**Comment by ccorcos** [comment]
Good point. So here are the two.

If `done` is terminal, then is there any reason to pass on the error?

```js
onDone = _.curry(function (f, source) {
    return source.consume(function (err, x, push, next) {
        if (err) {
            push(err)
            next()
        }
        else if (x === _.nil) {
            f()
            push(null, x)
        } else {
            push(null, x)
            next()
        }
    })
});

done = _.curry(function (f, source) {
    return source.consume(function (err, x, push, next) {
        if (x === _.nil) {
            f()
        } else {
            next()
        }
    }).resume();
});
```

**Comment by vqvu** [comment]
Nope. Instead, `self.emit('error', err)` is called so that errors don't get swallowed into the ether. This is what the code in #161 does.

**Comment by ccorcos** [comment]
ahhh. now I get it.

**Comment by ccorcos** [comment]
So what is "self" then? Can I use source?

```js
done = _.curry(function (f, source) {
    return source.consume(function (err, x, push, next) {
        if (err) {
            source.emit('error', err)
            next()
        }
        else if (x === _.nil) {
            f()
        } else {
            next()
        }
    }).resume();
});
```

**Comment by vqvu** [comment]
Self is source in this case.
