### ISSUE TITLE
Problem with buffers written to a stream in node.js environment

### ISSUE THREAD

**Issue by yangit** [caolan/highland#259]
This:
````
var f = _()
    .invoke('toString', ['utf8'])

f.write(new Buffer('no'));
f.end();

f.each(_.log);

//output is 'no' and that is fine
````
And this
````
var f = _()
    .invoke('toString', ['utf8'])
    .doto(_.log)

f.write(new Buffer('no'));
f.end();

f.each(_.log);

//output is [<Buffer 6e 6f>,<Buffer 6e 6f>] and that is beyond my comprehension.
````

At the same time those two are equivalent:
````
var s = _([new Buffer('yes')])
    .invoke('toString', ['utf8'])
    .each(_.log);

and

var s = _([new Buffer('yes')])
    .invoke('toString', ['utf8'])
    .doto(_.log)
    .each(_.log);
````
So this has to do something with .write method used to push buffers?

**Comment by vqvu** [comment]
Nope. Nothing to do with buffers. This is because each transform create a new stream and you need to `write` to the original one. In fact, `write` is only supported for streams that were constructed with `_()`.

Demo:

```javascript
var s = _(),
    s1 = s.invoke('toString', ['utf8']),
    s2 = s1.doto(_.log);

console.log(s === s1); // => false
console.log(s === s2); // => false
console.log(s1 === s3); // => false

// You must write to s.
s.write(new Buffer('no'));
s.end();

s2.resume();
// => 'no'
```

This is why you're better of using a [generator](http://highlandjs.org/#_%28source%29) and not `write` if you can help it.

**Comment by vqvu** [comment]
Since a lot of people seem to get this wrong, I've added some text to the docs that clarify this behavior: 8487ca37df9a0168ec040e5de17bdfb113430a8f
