### ISSUE TITLE
Passthrough failure

### ISSUE THREAD

**Issue by brian-gates** [caolan/highland#264]
var foo = $().map(function(){ return 'b'; }).doto($.log);
    $(['a']).pipe(foo).doto($.log).resume(); // a, a

Am I doing something wrong here?

**Comment by vqvu** [comment]
```javascript
var src = $();
var foo = src.map(function () { return 'b'; }).doto($.log);
$(['a']).pipe(src);
foo.resume(); // => b
```

You can only `pipe` to a stream constructed with `$()`.

Though I don't know why you're piping a highland stream to another highland stream. If you have a readable stream and needs to turn it into a highland stream, do this

```javascript
_(readable).map(..)
    .doto($.log)
    .resume();
```

If you really need to use `pipe`, do this

```javascript
src.pipe($())
    .map(...)
    .doto($.log)
    .resume();
```

**Comment by brian-gates** [comment]
Basically I want to write a duplex stream that other modules can `require`.

var foo = require('foo'); // a duplex stream

someotherstream.pipe(foo)// I expect the output of foo.

**Comment by vqvu** [comment]
Ah, I see. What you want is [pipeline](http://highlandjs.org/#pipeline).

```javascript
var foo = $.pipeline(function (s) {
    return s.map(...)
        .doto($.log);
});
```

**Comment by brian-gates** [comment]
Ah, I didn't see the second interface; I like that better.  Thanks!

It still seems strange to me how the example I gave behaves.  It seems counterintuitive.

**Comment by vqvu** [comment]
Think of it like this. A Highland stream is not a pipeline. It is a readable stream with an opaque source. Most Highland stream are not writable; only the ones created with `_()` are because they have no source. The transforms are not modifying the original stream, they are creating new ones. A stream with transforms is therefore purely readable.

It just so happens that the chaining syntax can make it look like you're modifying the original stream rather than creating new ones. There's no way around this though.

Note that it's no different to regular node streams in this sense.

```javascript
var through = require('through'),
    stream = require('stream');

var foo = through()
    .pipe(through(function (data) {
        this.queue('b');
    }))
    .pipe(map(function (data) {
        console.log(data);
        this.queue(data);
    }));

var rs = new Readable({objectMode:true});
rs.push('a');
rs.push(null);

rs.pipe(foo); // => a
```

**Comment by brian-gates** [comment]
Thanks for the explanation! :+1:
