### ISSUE TITLE
Features for coding processing pipelines

### ISSUE THREAD

**Issue by brentpayne** [caolan/highland#278]
I have been using highland to code processing pipelines and find myself always rewriting the same boilerplate around my functions.  So, I've gone ahead and forked the code and started to implement what I want as new transformations.

My typical pipeline looks like this.

```javascript
_(sentences).map(_curry(customErrorHandler(_.curry(addOriginalContext, tokenParser, 'tokens', 'raw')))
    .map(_curry(posErrorHandler(_.curry(addTransform, posTagger, 'pos', 'tokens')))
    \\\ and so on....
```
A couple of things are happening.  first I'm always taking in a stream of objects and return a new object with the original and new value.

```javascript
"cute kitten" 
\\ -tokenParser-> 
{tokens: ["cute", "kitten"], context: "cute kitten"}
```
Or I'm plucking on value applying a transform and adding it back into the original context object.

```javascript
 {tokens: ["cute", "kitten"], context: "cute kitten"} 
\\ -partOfSpeech(tokens) -> 
{pos:['ADJ', 'N'], tokens: ["cute", "kitten"], context: "cute kitten"}
```
Lastly, I want to continue processing if I hit an error, but I need to write out erroneous data to somewhere so we can:
  A: fix the problem
  B: get critical data into the database, even if we have a logic error in our code.

So I don't just need to know that there was an error, I need to know the value that created the error.

I've fork the code and am implementing code so my pipelines will look like the following:

```javascript
_(sentences).context(tokenParser, 'tokens', 'raw')
    .errors(tokenizationErrorHandler)
    .transform(partOfSpeech, 'tokens', 'pos')
    .errors(posErrorHandler)
```

To do this, I've done the following

  *  allowed the original value to be passed along with any errors, but only for my new transforms
  *  created a npcurry function that curries function with *n* required parameters followed by optional parameters
  * created a *context* primitive that maps to a dictionary with the transformed value and original context
  * creating a *transform* primitive that operates on member variables

I would like to add these back into the code base, as they are very helpful for these types of processing pipelines.  I'd also like to suggest always sending the value that caused an error along with the error.  This greatly simplify error handling as it allows *.errors* more flexibility in the types of errors it can successfully handle.

The main reason I want these new primitives is that it simplifies my transformation function to only be concerned about the data transformation and be pipeline agnostic.

Guidance is requested.   What are other elegant ways to handle this?

**Comment by brentpayne** [comment]
current branch is https://github.com/cursivelabs/highland
The tests are the best place to look at how I'm using the requested changes.

**Comment by vqvu** [comment]
> `npcurry`

Optional arguments are confusing when combined with currying, so this will probably not make it into the library. For example, suppose you have an operator with this signature.

```javascript
Stream.prototype.foo = function (a, /* optional */ b) {
...
}
```

and you call `_.foo(3, _())`, does the `_()` get set to `b` or is it equivalent to `_().foo(3)`? What about `_.foo(3)(_())`? If they do different things, why? They don't *look* like they do different things.

> `context` and `transform`

I don't see an implementation for `transform` in your fork, but these methods are pretty specific to your application, IMO, so I don't think we should add them to Highland core, as we don't want the library to be a kitchensink. For now, you can implement them as `through`-style transforms

```javascript
function context(f, value, context) {
    ...
}

_(sentences).through(context(tokenParse))
    ...;
```

> context with errors

I can see this being useful in general, but we'd need to modify the error or wrap it in a Highland-specific one. Both would break backcompat.

Plus, it's hard to do this in a general way. For instance, the context is obvious in transforms like `map` and `flatMap`, but what about `sortBy`? What's the context for that? The entire array?

`uniqBy` takes a comparison function. What's the context if that fails? It's not just the latest item, because the cause could be from the second argument. Same issue with `reduce` and `scan` and pretty much any function that takes multiple arguments.

My initial reaction is that you need to make your `tokenParser` throw something that contains the context if you need the context.

You can do this at definition time by doing something like this if you also want to guard against logic error:

```javascript
function addContextOnError(f) {
    return function () {
        try {
            return f.apply(this, arguments);
        }
        catch (e) {
            e.context = x;
            throw e;
        }
    };
}

var tokenParser = addContextOnError(function tokenParser(x) {
    ...
});
```

**Comment by vqvu** [comment]
Of course, you could also make your custom `context` and `transform` add the context object instead of using `addContextOnError`. That's only useful if you use a standard transform directly like `map`.

**Comment by svozza** [comment]
The context with errors use case sounds an awful lot like the `Either` monad, hence why is plays so nicely with `map`. You could probably use something like [Monet.js](https://github.com/cwmyers/monet.js) or [Sanctuary](https://github.com/plaid/sanctuary) to get this sort of functionality. That said, I've only started playing around with this stuff very recently though so I could well be wrong!

**Comment by vqvu** [comment]
The `Either` monad doesn't take care of the context (you probably need to compose a `State` monad to get that), but it can be used to sidestep stream errors directly. It lets you pass down logic errors as *values* in a Highland stream instead of as errors so that errors can be reserved for fatal, stop the stream errors. IMO, if you can continue after an error, then it's not really a *stream error*, it's a stream value that represents an error in your application.

Doing it this way would give you better behavior with some transforms. For instance, `take` doesn't count errors, so `_([1, 2, 3, 4]).map(f).take(1);` can give you any number of errors depending on when `f` throws. Using the `Either` monad, you will always get one error or value. Whether or not this matters to you depends on the application.

**Comment by svozza** [comment]
Ah yes,  I was getting confused there, an `either` can't hold two values simultaneously. I really like your idea of using them to communicate logic errors,  it makes a lot of sense.

**Comment by brentpayne** [comment]
@vqvu @svozza ,  thanks for the in-depth feedback.  I am running on 3 hours sleep, but I agree that the functions should be a plugin and my only place of contention is how errors are handled.  This comes down to the semantics of if an error is a *stream error* or an *exception* to be handled.  

I'll be back in a day with more feedback, but if you do add plugins into v3.0.0.  I'd suggest the `transform` to be added to an object transformation plugin along with some current primitives, `pick`, `pickBy`, etc.  It is basically a `pick` and `map` to member variable.
