### ISSUE TITLE
[question] Consume stream multiple times, or multiple asynchronously attached observers

### ISSUE THREAD

**Issue by brian-gates** [caolan/highland#299]
I'd like to pass a stream around much like a promised value such that multiple consumers can act on the  produced value as soon as the value and consumer are both ready.  I feel like there's a clever way to do this that I'm missing.

Probably easier to explain with broken code:

    var log = $.ncurry(2, $.log);

    var foo = _(function (push) {
      push(null, 'foo');
      push(null, _.nil);
    });

    foo
      .doto(log('log1')) // works!
      .flatMap(function () {
        return foo.observe(); // by this point the stream has already ended :(
      })
      .apply(log('log2')) // never reached :(
    ;

Desired result is 
    log1 foo
    log2 foo

**Comment by vqvu** [comment]
If you knew the number of consumers before consumption, you could do all of the `observe` a priori and just return them all (in an array or another stream).

Alternatively, if you don't know about all consumers, but you know when there will be no more consumers, you can have each consumer do an `observe`, to register their interest, so to speak. Once no more consumers are forthcoming, call `resume` on the original stream. This technically breaks the "as soon as both are ready" requirement though, because you would be waiting until *all* consumers register their interest (not the same as when they're ready). So if you have a fast stream, you could potentially have both the value and an (early) consumer be ready but not able to proceed. This mostly works if you can get all consumers to `observe` in a short amount of time.

A third way is to do two `observe`s, operate on one, and pass the other on. Something like this.
```javascript
function consume(s) {
    giveToConsumer(s.observe());

    // Split off another fork.
    var res = s.observe();

    // Resume the original. This will start providing values to the consumer
    // if they are ready. At the same time, the `res` stream will buffer those
    // values for the next consumer.
    s.resume();
    return res;
}
```
I wouldn't recommend doing this if you have a lot of consumers though (order of many thousands), since each time you consume, you actually tack on an extra part in the pipeline. More parts means more overhead from running Highland's code and not your own. It also means that once you get a long enough pipeline, you'll get a stack overflow.

You can also manually implement the appropriate operator. That's the ideal solution, but it could get rather complicated to do right. A lot of book keeping involved

**Comment by brian-gates** [comment]
It sounds like the best solution would be to just wrap the stream in a memoizer function :)

**Comment by vqvu** [comment]
Yes. That would be the best solution. Though I can imagine two ways to memoize a stream. You either memoize as you go (i.e., the equivalent of [replay](http://reactivex.io/documentation/operators/replay.html)) or wait until the stream ends, then save that array, and emit it all to consumers at once. The first is the "ideal solution" I was talking about. The second is far easier to get right.

If you do implement `replay`, please feel free to contribute it back. :)

**Comment by brian-gates** [comment]
Awesome thanks for the insights.
