### ISSUE TITLE
Question: Retrying an operation when an error occurs

### ISSUE THREAD

**Issue by bapti** [caolan/highland#308]
I've posted a question on SO about retrying an operation when it errors

http://stackoverflow.com/questions/30378485/retrying-a-operation-with-highlandjs-when-an-error-occurs

In the callback for the error I just pass the operation data with some attached error data.  Is it possible to retry the operation in this flow.  

I've got it working at the moment by building in the retry functionality into my `doOperation` function but it feels like it would be neater to handle in the error callback.  I'm probably misusing the API though.

```coffeescript
highland( arrayOfOperations )
    .map( doOperation )
    .parallel( numberOfParallelOperations )
    .errors( (operation) ->
        if operation.attempts < maxRetries
          # retry the operation
    )
    .each( (operation) ->
        # operation success
    )
    .done(
        # all complete
    )
```

**Comment by vqvu** [comment]
You can't handle this in the `errors` callback. It was only meant for you to look at the errors individually, possibly replacing that error with some other value, but not for higher-level stream operations like retry.

In general though, there's no way to do retries downstream, because Highland streams are single-use, so unless you also push the operation to retry downstream, there's no way to just say "redo this".

You could still make a generic retry functionality though. For example:

```javascript
function retryOnError(op, maxRetries) {
    return function (x) {
        return op(x).consume(function (_err, _x, push, next) {
            if (_err) {
               if (maxRetries > 0) {
                   // Retry if allowed. Uses next to delegate to a new stream.
                   next(retryOnError(op, maxRetries - 1)(x));
               } else {
                   // Too many retries. Just stop.
                   push(_err);
                   next();
               }
            } else {
                // Pass-through values.
                push(_err, _x);
                if (_x !== _.nil) {
                    next();
                }
            }
        }
    }
}

highland( arrayOfOperations )
    .map( retryOnError(doOperation, 5) )
    .parallel( numberOfParallelOperations )
    .errors( (operation) ->
        # Retried more than 5 times but still failed. Handle somehow.
    )
    .each( (operation) ->
        # operation success
    )
    .done(
        # all complete
    )
```

The code above assumes that you only emit an error at the beginning, so you don't have something like `5 -> 5 -> error`, since that would cause the first two `5` to be emitted *and* cause a retry, which likely causes two more `5` to be emitted.

**Comment by bapti** [comment]
Thanks a million for your answer.  I ended up plugging in (node-retry)[https://github.com/tim-kos/node-retry] which does the retry of the task nicely
