### ISSUE TITLE
Highlevel guideline

### ISSUE THREAD

**Issue by kharandziuk** [caolan/highland#315]
I'm trying to use a library a few days and it's still unclear for me – is highland.js a competitor of Rx/Bacon? Should I use it for Reactive-style programing? If yes, why a lot of primitives are absent (takeWhile, interval etc)? Is it a kind of design decision(like with [step](https://github.com/creationix/step) library)  and  I should implement them by hand?

**Comment by vqvu** [comment]
The answer to all of your questions is "yes". At a high level, you can use highland for reactive-style programming.

The major semantic differences are
- Highland strives to be as lazy as possible. The stream won't request data until it absolutely needs it, so you can use it to sequence side effects. I don't think this is true for RxJS (I know that RxJava will sometimes request elements it doesn't yet need to improve throughput).
- Highland streams are use-once. Rx Observables can usually be subscribed to multiple times.
- Highland errors do not end a stream like in Rx. They are simply another (specially treated) value.

The missing operators are partly by design and partly because no one has gotten around to implementing them (the missing `takeWhile` is an example of the latter). We don't want to maintain a huge kitchen sink of operators, but PRs for generic and useful operators are still accepted.

There's also the fact that we cannot reasonably maintain an equivalent library of operators due to the heavy use of optional parameters in Rx. All of our operators are curried and placed on the top-level export, so we can't support optional parameters at all.
