### ISSUE TITLE
pipe with corked stream

### ISSUE THREAD

**Issue by kharandziuk** [caolan/highland#317]
consider the code below:
```
H = require('highland')
fs = require('fs')
readS = H(fs.createReadStream('gama.txt'))
writeS = fs.createWriteStream('kapa.txt')

writeS.cork()
readS.pipe(writeS)
readS.fork()
  .done(->writeS.end())
```
after the run the `kapa.txt` is empty(I expect to see a content of 'gama.txt'.

If I change `fs.createReadStream('gama.txt')` to `[new Buffer('one')]` everything works as expected.

**Comment by vqvu** [comment]
`cork` causes `Writable#write` to return `false` once you filll up the buffer. This causes backpressure to the source stream which pauses it. You never `uncork`, so the stream can never resume.

**Comment by kharandziuk** [comment]
@vqvu. You answer looks reasonable but it still unclear for me why it works in case of buffers.  

```
H = require('highland')
fs = require('fs')
readS = H([
  new Buffer('one'),
  new Buffer('two')
])
writeS = fs.createWriteStream('kapa.txt')

writeS.cork()
readS.pipe(writeS)
readS.fork()
  .done(->writeS.end())
```

Can you explain?

**Comment by vqvu** [comment]
Because the fs stream has a `highWaterMark` before it'll reject writes, so if you write less than that value, it'll never exert backpressure. This allows your stream to end and for you to call `writeS.end`, which `uncork`s the stream and causes the write. By default, I think the `highWaterMark` is 65KB or something? If you make your buffers really big, it bet you won't see the a write either.
