### ISSUE TITLE
Why not _.consume ?

### ISSUE THREAD

**Issue by asafyish** [caolan/highland#427]
Hi,

I saw in the docs and even in a few issues here, that if I want to do asynchronous actions, I better use .flatMap.
Now, I am using .consume for asynchronous actions, and it's working great.
Am I missing something ? Maybe causing memory leaks along the way ?

Thanks.

**Comment by vqvu** [comment]
`consume` is a lower-level API than `flatMap` is, so it's naturally more powerful, but harder to use. With `consume`, you have to deal with `nil` and `next` and errors, and in general more bookkeeping/boilerplate to do.

That's why we recommend that you use `flatMap` if it meets your needs. One thing that `flatMap` does for you is catch exceptions thrown from your mapper function and re-emit them as errors in the stream. `consume` won't do that. If you throw an exception in your `consume` handler, you won't know where it will end up.

So there's nothing wrong with using `consume`. Sometimes you'll need to use it, but `flatMap` is easier to use, and most of the time, it's good enough.

**Comment by asafyish** [comment]
Ok Thanks !
