### ISSUE TITLE
Memory issue with mapping async functions

### ISSUE THREAD

**Issue by DrDanRyan** [caolan/highland#432]
I am migrating a mongodb database with filesystem storage of images to a mongodb database with gridFS storage using the standard node mongodb driver. I have around 15,000 photo documents with associated files that I am migrating and I tried something like this:
```javascript
  function populatePhotos(mainCb) {
    var photosBucket = new mongodb.GridFSBucket(db, {bucketName: 'photos'});
    var cursor = db.collection('oldPhotos').find();

    _(cursor.stream())
      .map(_.wrapCallback(insertPhoto)).mergeWithLimit(50)
      .done(mainCb);

    function insertPhoto(oldPhotoDoc, cb) {
        // a few async operations to collect photo metadata and other info followed by
        // streaming from filesystem to gridFS Bucket using basic node pipe
        // control flow with async.auto that calls cb when streaming to gridFS is complete
    }
  }
```

When I run this, there is some sort of memory leak going on, as more documents have been processed, the system memory becomes totally consumed. My node process got up to something like 10GB of memory use. Curiously, the same thing happens when mergeWithLimit is replaced with parallel(1). 

I am assuming that when each wrapped insertPhoto stream is completed (cb called by async.auto) all the memory allocated inside of insertPhoto is freed. Is this not the case? Am I missing something fundamental about the way this works?

I also tried returning a stream directly instead of wrapping a callback and ran into the same issue
```javascript
function insertPhoto(doc) {
  return _(function(push, next) {
    // common setup here

    async.auto({
      // multiple async ops here that handle own errors
    }, () => {
      push(null, null);
      push(null, _.nil);
    });
  });
}
```
I also tried a basic `flatMap` and ran into the same issue.

**Comment by vqvu** [comment]
The way you're using Highland is correct. I don't see anything that would obviously cause a memory leak. Highland shouldn't see any memory that is allocated inside of `insertPhoto`. It simply calls the function and wait for the callback, so unless you're leaking references to memory created by `insertPhoto`, I don't see how there would be a memory leak.

The other possibility is that some bug is causing back-pressure to not function properly and forcing the stream to buffer your entire `oldPhotos` collection. How big is your data set?

Can you try the following? First, update to 1.6.0 if you haven't already. We had a different issue with mongo cursor streams #388 and maybe that fixes this problem too.

If this problem is present on 1.6.0, I want to see if there really is some backpressure issue. The most likely place is when Highland interacts with the cursor stream. You can pipe the cursor stream through another stream to see what it actually emits.

For example, I ran this test code.
```javascript
function populatePhotos(db, mainCb) {
    //var photosBucket = new mongodb.GridFSBucket(db, {bucketName: 'photos'});
    // I have 15000 fake documents in here.
    var cursor = db.collection('coll').find();

    var s = _();

    // We override s.write here so that we can see what's being pushed
    // to the stream.
    var oldWrite = s.write;
    s.write = function (x) {
        console.log(x);
        return oldWrite.call(s, x);
    };

    // readable.pipe(_()) is roughly (not exactly) equivalent to
    // _(readable).
    cursor.stream()
      .pipe(s)
      .map(_.wrapCallback(insertPhoto))
      .mergeWithLimit(50)
      .done(mainCb);

    function insertPhoto(oldPhotoDoc, cb) {
        // a few async operations to collect photo metadata and other info followed by
        // streaming from filesystem to gridFS Bucket using basic node pipe
        // control flow with async.auto that calls cb when streaming to gridFS is complete

        // This is me faking an async operation.
        setTimeout(cb, 1000);
    }
}

MongoClient.connect(url, function(err, db) {
    populatePhotos(db, function () {
        console.log('done');
        db.close();
    });
});
```

If backpressure is working correctly, then you should see data slowly being displayed. If it isn't, you'll see data much faster. When I run the code above, I see 50 documents printed out every second, which is the expected behavior.

You can also try to use [node-inspector](https://github.com/node-inspector/node-inspector) to see what is actually taking up all of your memory. Here's some simple instructions: https://github.com/felixge/node-memory-leak-tutorial. Highland streams' constructor is named `Stream`.

**Comment by DrDanRyan** [comment]
So, it turns out that there was a serious memory leak issue with the GridFSBucket class from the mongodb package. It has been fixed and a pull request has already been issued.  It had nothing to do with highland.

Thanks for your help though; I really like this flow control pattern for performing async tasks on a large collection of objects.
