### ISSUE TITLE
Highland and send

### ISSUE THREAD

**Issue by ronag** [caolan/highland#433]
How do I use https://www.npmjs.com/package/send with highland?

i.e. the following

```javascript
_(send(req, path))
  .pipe(res)
```

will fail with:

```
  if (!res.getHeader('Accept-Ranges')) res.setHeader('Accept-Ranges', 'bytes');
           ^

TypeError: res.getHeader is not a function
    at SendStream.setHeader (/Users/ronagy/Projects/GitHub/boffins/nxt/nxt-media/nxt-media-store/node_modules/send/index.js:752:12)
    at SendStream.send (/Users/ronagy/Projects/GitHub/boffins/nxt/nxt-media/nxt-media-store/node_modules/send/index.js:531:8)
    at onstat (/Users/ronagy/Projects/GitHub/boffins/nxt/nxt-media/nxt-media-store/node_modules/send/index.js:624:10)
```

while this works:

```javascript
send(req, path)
  .pipe(res)
```

**Comment by vqvu** [comment]
It looks like `send` [overrides `pipe`](https://github.com/pillarjs/send/blob/master/index.js#L431) to save a reference to the piped-to stream, which it then eventually uses to [send its data](https://github.com/pillarjs/send/blob/master/index.js#L518). The *real* `pipe` happens [here](https://github.com/pillarjs/send/blob/master/index.js#L694).

When you do `_(send(req, path))`, Highland tries to pipe the `SendStream` to a Highland stream. But `send` assumes that the piped-to stream is a `Response` object. That's why you get that error. I'm not sure what you're trying to do, but it doesn't look like it's possible to wrap a `SendStream` in a Highland stream.
