### ISSUE TITLE
timeout?

### ISSUE THREAD

**Issue by ronag** [caolan/highland#439]
How would I go about implementing something like `Observable.timeout`?

I tried doing it with `consume`. However, it won't be invoked until the source stream passes something along, which is what I want the timeout for...

**Comment by vqvu** [comment]
Low-level timing-based operators needs to use `pull` rather than `consume`, since the implementation is pull-based (producing data) rather than push-based (responding to data). Typically you return a generator stream that calls `pull` on the result to get data when it needs it.

The following is untested:

```javascript
function timeout(ms) {
    return s => {
        var timeout;
        return _((push, next) => {
            timeout = setTimeout(() => push(new Error('Stream did not emit in time')), ms);
            s.pull((err, x) => {
                push(err, x);
                clearTimeout(timeout);
                if (x !== null) {
                    next();
                }
            })
        })
        // Use stopOnError to replicate Rx's error behavior.
        // You don't necessarily need it.
        .stopOnError((err, push) => push(err));
    };
}
```
