### ISSUE TITLE
Through node stream & node proc?

### ISSUE THREAD

**Issue by ronag** [caolan/highland#444]
Would be nice if through supported node streams with error forwarding..

e.g. not sure if this would work

```javascript
function through(s) {
  if (s instanceof Stream) {
    return _([
      this.filter(() => false), // Only errors
      _(this.pipe(s)) // s might be a write stream in which case only errors or _.nil ('finish') should be forwarded
    ])
    .merge()
 }
 // ...
```
In particular I would like this for:

```javascript
const md5 = await new Promise((resolve, reject) =>
  _([
    s.fork().through(fs.createWriteStream(...)),
    s.fork().through(crypto.createHash('md5').setEncoding('hex')),
  ])
  .reduce('', (xs, x) => xs + x)
  .stopOnError(reject)
  .toArray(([md5]) => resolve(md5))
)
```

**Comment by ronag** [comment]
Another example that would be nice to have a operator for:

```javascript
const proc = spawn(...)
s.pipe(proc.stdin)
// TODO: How to forward errors from s to output?
return _(proc.stdout)
```

**Comment by ronag** [comment]
The key question here is whether `Writeable` streams can be converted into highland streams.

**Comment by vqvu** [comment]
`through` currently support node Duplex streams. Anything that is both a Readable and Writable. I don't think it makes sense to support Writable streams in that operator, since it's meant to be a generic transform of sorts. I also don't want to go down the rabbit hole of trying to detect writable versus duplex versus highland streams.

Same with direct support for the Process/ChildProcess objects. We don't want the core highland library to be a kitchen sink of operators. Especially since `through` is an extension point that people can use to implement their own library of operators. 3.0.0 will have even better support for extensions.

That said, it certainly possible to convert a Writable into a highland stream in the way that you want.

```javascript
function wrap(writable) {
    // The err/end/push gymnastics is because there's currently no way to
    // push an error outside of a generator, and the generator is called
    // lazily, so you may not bind to the events on time.
    var err, end, push;
    writable.on('error', _err => {
        if (push) {
            push(_err);
            push(null, _.nil);
        } else {
            err = _err;
        }
    }).on('finish', () => {
        if (push) {
            push(null, _.nil);
        } else {
            end = true;
        }
    });
    
    return _((_push, _next) {
        if (err) {
            _push(err);
            _push(null, _.nil);
        } else if (end) {
            _push(null, _.nil);
        } else {
            push = _push;
        }
    })
}
```

You could also turn the Writable into a promise first and wrap the promise.

```javascript
function wrap(writable) {
    return _(new Promise(res, rej) {
        writable.on('error', rej);
            .on('finish', res);
    }).filter(nothing => false);
}
```

**Comment by ronag** [comment]
@vqvu: 

So you suggest something like?

```javascript
import _ from 'highland'
import { spawn } from 'child_process'

export function wrapWritable(writable) {
  return _(new Promise((res, rej) => writable
    .on('error', rej)
    .on('finish', res)
  )).filter(nothing => false)
}

export function throughProc(...args) {
  return s => {
    const proc = spawn(...args)
    return _([
      s.filter(() => false),
      _(proc.stdout),
      wrapWritable(s.pipe(proc.stdin)),
    ])
  }
}
```

**Comment by vqvu** [comment]
It should be

```javascript
return _([
      s.observe().filter(() => false),
      _(proc.stdout),
      wrapWritable(s.pipe(proc.stdin)),
    ])
```

You can't consume from the same stream twice without `fork` or `observe`. But do you even need the `s.observe().filter(() => false)` in the first place? Wouldn't `proc.stdin` emit `finish` when all data from `s` has been piped to it?

> Do we have anywhere we can put these kind of misc code snippets for others to re-use?

Not really. A good place might be the docs site, but someone would have to do the legwork of setting up a different page. The wiki would be easier, but as far as I can tell, github doesn't allow PRs against the wiki. I'm open to ideas. Many people have requested a highland "cookbook".

**Comment by ronag** [comment]
> But do you even need the s.observe().filter(() => false) in the first place?

How would errors from `s` be propagated without?

**Comment by vqvu** [comment]
> How would errors from s be propagated without?

Oh, it's for error propagation. You're better off binding an `on('error')` to the stream and emitting it that way. The reason is that `s.pipe` will call `emit('error', error)` when it encounters an error. If you don't bind `on('error')`, that error will be thrown, and your pipeline will end up failing at some indeterminate time.

You'll want to implement the full through-that-passes-on-errors then (of which `wrapWritable` is a component).

```javascript
function throughWritable(writable) {
    return s => {
        var sawStreamError = false;
        var errors = _(new Promise(res, rej) {
            s.stopOnError(err => {
                sawStreamError = true;
                rej(err);
            }).on('end', () => {
                if (!sawStreamError) {
                    res();
                }
            }).pipe(writable);
        }).filter(() => false);
        
        return _([errors, wrapWritable(writable)])
            .merge();
    };
}
```

> I don't think observe is the correct approach, fork would probably be the right way.

Since you're just doing a `merge` of all these streams, `observe` is just fine. The shared backpressure from `fork` doesn't help here, since `merge` consumes from the streams all at once.

**Comment by ronag** [comment]
@vqvu: You are loosing me a little

> The reason is that s.pipe will call emit('error', error) when it encounters an error. If you don't bind on('error'), that error will be thrown, and your pipeline will end up failing at some indeterminate time.

Isn't that why I'm wrapping the pipe call in a `wrapWritable` so that errors are propagated from there as well?

What does `throughWritable` do? The name is a little confusing?

My thoughts:

```javascript
_([
      s.observe().filter(() => false), // Propagate errors from s
      _(proc.stdout), // Propagate items
      wrapWritable(s.pipe(proc.stdin)), // Propagate errors from pipe, i.e "s.pipe will call emit('error', error)"
    ])
```

**Comment by vqvu** [comment]
> Isn't that why I'm wrapping the pipe call in a wrapWritable so that errors are propagated from there as well?

What I mean is, when you do `s.pipe(writable)`, *both* `s` and `writable` may emit errors. `s` does it if there is some error in its pipeline. `writable` does it if there is some error writing the values. Thus, it is not enough to call `s.pipe(writable).on('error')`. You must actually do `s.on('error', handler).pipe(writable).on('error', handle)`.

> What does throughWritable do?

It implements `pipe` with error forwarding. `throughWritable(writable)(s)` returns a stream that ends when `writable` emits `finish` and will emit any error that `s` or `writable` emits. This is what you originally wanted.

> Where does it fit in with wrapWritable and throughProc?

It uses `wrapWritable` to grab the errors and `finish` event from the input writable.

`throughProc` should be implemented using `throughWritable`.

```javascript
return s => {
    const proc = spawn(...args)
    return _([
      throughWritable(proc.stdin)(s),
      _(proc.stdout),
    ])
    ...
```

> I need to think about this.

Basically, you normally use `fork` if you want one of two things to happen:

1. A slow child should automatically slow down all other children so that it doesn't get overwhelmed.
2. If a child is paused, all other children should be paused as well so that they don't do uncessary work.

In this case, the observing stream isn't doing any work. It is very fast and will never slow down the other stream, so (1) doesn't apply*. You are also using `merge`, which applies backpressure to all of its source streams equally. It is not possible to get to a situation where the `s.filter` stream is paused and the `wrapWritable` stream is not, so (2) doesn't apply. Thus, you don't need to use `fork`.

*Note that the `wrapWritable` stream *is* slow, because it is piping to a writable. But since the `s.filter` stream is an observer, and can't pull data from the source, we are still OK. The `wrapWritable` stream will pause the source when it is waiting for writes to complete, which will cause the `s.filter` stream to not see anything from the source, effectively pausing it.

**Comment by ronag** [comment]
Thanks!
