### ISSUE TITLE
fork ending earlier than others

### ISSUE THREAD

**Issue by ronag** [caolan/highland#448]
I've noticed that if a fork ends before another fork then the stream is stopped.

How should I handle the following situation?

```javascript
const s = _(fs.createReadStream(...))
_([
  s.fork().through(analyze1()),
  s.fork().through(analyze2()),
  s.fork().through(analyze3()),
  s.fork().through(analyze4()),
]).merge()
  .each(value => console.log(value))
```

Where each `analyze` function might or might not consume the entire stream before `_.nil`?

I could use `observe`. However, that might cause out of memory errors...

**Comment by vqvu** [comment]
`fork` can't be properly used with `take` or basically anything that ends early. This is a known issue and can't be fixed without changing some behavior in a backwards incompatible way. This is fixed in the version 3.0.0 that we are developing.

Right now, you either have to not end forks early or forcibly destroy them when you're done (in 3.0 the destroy is done automatically).

```javascript

var s = _([1, 2, 3, 4]);
var fork1 = s.fork();
var fork2 = s.fork();

fork1.take(1)
    // Destroying fork1 will relieve the back pressure and
    // allow fork2 to continue.
    .consume((err, x, push, next) => {
        push(err, x);
        if (x === _.nil) {
            fork1.destroy();
        } else {
            next();
        }
    })
    .each(i => console.log('fork1', i));

fork2.each(i => console.log('fork2', i));

// => fork1 1
// => fork2 1
// => fork2 2
// => fork2 3
// => fork2 4
```
