### ISSUE TITLE
Problem with fork and take 

### ISSUE THREAD

**Issue by dignifiedquire** [caolan/highland#459]
Hey, first of all thanks for a great library, I really enjoy working with highland. Unfortunately I've run into the following issue:

```js
const _ = require('highland')

const s = _([1, 2, 3])
const s1 = s.fork().take(1)
const s2 = s.fork().drop(1)

const t = _(['hello'])

const res = t
  .zip(s1)
  .flatMap((args) => {
    console.log(args)
    // I need both 'hello'  and 1 here to transform the values on s2 in my actual use case

    return s2
  })
  .toArray()

console.log(res)
// => undefined
// expected
// ['hello', 1]
// 2
// 3
```

which I can't seem to resolve (even with the 3.0.0 beta that supposedly has a fix for `take` backpressure issues).

Any pointers to why this does not work, or how I could solve this in a better way?

**Comment by vqvu** [comment]
`s1` and `s2` share backpressure. You are consuming from `s1` (from `t.zip(s1)`) without consuming from `s2`. The zip never emits a value (because `s1` is waiting for `s2` to be consumed), so the `flatMap` never executes. This is a different deadlock issue than the one 3.x fixes (which is the fact that `take` still exerts backpressure even after it completes). You must actively consume from a `fork` for it to relieve backpressure---even if the fork will simply drop the data element once it gets it (like `s2` does).

I think the best way to make this work is to use `pull` rather than a combination of `fork` and `take`. Here's an example. `split` returns two streams `head` and `tail` that each emit elements from their respective part of the source. Because of laziness, `tail` depends on `head` to be consumed, but `head` *does not* depend on `tail`.

The `head` stream uses `pull` to fetch the first element and emits it. The `tail` waits until the `head` stream is done before calling `next` to redirect all remaining output from `stream` to itself. This can be generalized to allow `head` to contain the first `n` elements rather than just the first.

```javascript
function split(stream) {
    var yieldFn = null;
    const head = _((push, next) => {
        stream.pull((err, x) => {
            push(err, x);
            push(null, _.nil);

            if (yieldFn) {
                yieldFn(stream);
            } else {
                yieldFn = true;
            }
        });
    });

    const tail = _((push, next) => {
        if (yieldFn) {
            next(stream);
        } else {
            yieldFn = next;
        }
    });

    return [head, tail];
}

const [head, tail] = split(_([1, 2, 3]));
const t = _(['hello']);

const res = t
    .zip(head)
    .flatMap((args) => {
        console.log(args);
        return tail;
    })
    .each(console.log);
// => [ 'hello', 1 ]
// => 2
// => 3
```

This should work with any highland version.

**Comment by dignifiedquire** [comment]
Thanks for the quick response and the explanation! Your solution works exactly as I needed :)
