### ISSUE TITLE
Q - Stream not ended causes memory leak?

### ISSUE THREAD

**Issue by ronag** [caolan/highland#465]
If a stream is not ended (i.e. `push(null, _.nil)`) would that cause a memory leak?

e.g. if wrapping a NodeJS request object as a highland stream and the client aborts the request, then the `end` even is never called, instead only the `close` event is called. Would this cause a memory leak?

```javascript
function (req, res, next) {
  const ws = ws.createWriteStream('dummy.txt')
  req.on('close', () => {
    ws.end()
    console.log('Client Aborted Request') // Memory leak?
  })
  _(req).pipe(ws)
}
```

**Comment by vqvu** [comment]
Not in the example you give, but it is possible in certain situations.

For example `pipe` will add a `on('drain')` handler to the destination and will only remove it once the stream has ended (not actually true in 2.7.1 but fixed in #466). So if you `pipe` an infinite stream to some destination that you are keeping around (e.g., `process.stdout`), you'll have a memory leak since there is a path from the destination to the source stream via the `drain` handler.

Similarly, some higher-level operators like `merge` will keep source streams around until they emit `nil`, so if the merged stream is long-lived, you'll have a memory leak.

In these cases, you can manually call `end()` on the stream if necessary.
