### ISSUE TITLE
Best practices for parallelizable processes?

### ISSUE THREAD

**Issue by peterkhayes** [caolan/highland#498]
I frequently use Highland to process CSVs of data.  Each row of the CSV requires several asynchronous steps (mostly I/O), but they can be done in entirely in parallel with each other.

My code currently looks like this:
```js
_(csvStream)
  .map(parse)
  .flatMap(doAsyncTask1)
  .flatMap(doAsyncTask2)
  .flatMap(doAsyncTask3)
  .done(logAndExit);
```
I then split the CSV into parts and run multiple node processes in parallel on each part.  However, this seems silly - I'd love to do the work all within one node process.  My ideal API would be something like this, where a stream can be split into multiple consumers, such that as new data becomes available, the next available consumer handles it:
```js
const source = _(csvStream)
  .map(parse);

function makeFork (source) {
  return source
    .parallelFork()
    .flatMap(doAsyncTask1)
    .flatMap(doAsyncTask2)
    .flatMap(doAsyncTask3);
}

const processors = [makeFork(source), makeFork(source), ...] // etc
processors.merge().done(logAndExit)
```

But I can't use the regular `fork` for this, since each fork processes the same data.  I'm wondering what the standard practice for dealing with this sort of situation is.

**Comment by vqvu** [comment]
The `parallelFork` API you've described doesn't exist, and it's actually somewhat tricky to implement. Fortunately, I don't think you need it. Doing `map(...).parallel(n)` should get you what you want.

```javascript
// For each async tasks, there are numProcs processors running in parallel. They execute
// the task on each line as soon as they are free and new data is available.
const numProcs = 5
_(csvStream)
  .map(parse)
  .map(doAsyncTask1).parallel(numProcs)
  .map(doAsyncTask2).parallel(numProcs)
  .map(doAsyncTask3).parallel(numProcs)
  .done(logAndExit);
```

Or to make more explicit what's going on,
```javascript
function parFlatMap(f, n) {
    return s => s.map(f).parallel(n);
}

_(csvStream)
  .map(parse)
  .through(parFlatMap(doAsyncTask1, numProcs))
  .through(parFlatMap(doAsyncTask2, numProcs))
  .through(parFlatMap(doAsyncTask3, numProcs))
  .done(logAndExit);
```

The above means up to `numProcs` of *each* async tasks can run at the same time (for a total of `3 * numProcs` parallel tasks). If you want to restrict to `numProcs` parallel consumers at the same time, do something like this

```javascript
// numProcs processors. Each processor executes all three async tasks in order before
// picking off the next line from the CSV stream.
_(csvStream)
  .map(parse)
  .map(x => doAsyncTask1(x)
    .flatMap(doAsyncTask2)
    .flatMap(doAsyncTask3))
  .parallel(numProcs)
  .done(logAndExit);
```

You can also use [mergeWithLimit](http://highlandjs.org/#mergeWithLimit) instead of `parallel` if you don't care about preserving the order of results.

**Comment by peterkhayes** [comment]
Awesome, thanks!  I was a bit confused about parallel from the docs - I thought it might do what you've mentioned, but it wasn't clear exactly what it would return
