### ISSUE TITLE
Proper HTTP upload with NodeJS & highland

### ISSUE THREAD

**Issue by ronag** [caolan/highland#508]
Given the new release, with some nice fixes, I'm trying to port some of my RxJS & Nodejs Streams code over to highland.

This is the original code:

```javascript
const progress$ = Observable
  .create(o => {
    const fileStream = fs.createWriteStream(filePath, { flags: 'wx' })
    const hasher = crypto.createHash('md5')

    req.on('data', buf => {
      hasher.update(buf)
      if (!fileStream.write(buf)) {
        req.pause()
      }
      o.next({
        position: fileStream.bytesWritten
      })
    })
    req.on('error', ::o.error)
    req.on('end', ::fileStream.end)
    req.on('close', () => o.error(new Error('upload cancelled')))
    fileStream.on('drain', ::req.resume)
    fileStream.on('error', ::o.error)
    fileStream.on('close', () => {
      o.next({
        md5: hasher.digest('hex'),
        position: fileStream.bytesWritten
      })
      o.complete()
    })
    return () => fileStream.destroy()
  })
```

This is my highland code so far...

```javascript
const req$ = _(req, onFinished)
const progress$ = _([
  req$
    .fork()
    .through(crypto.createHash('md5'))
    .map(md5 => ({ md5 }))
  req$
    .fork()
    .through(fs.createWriteStream(filePath, { flags: 'wx' }))
]).merge()
```

My highland implementation is missing a few things:
 - `{ position }` updates and final position.
 - `req.on('close')` should be an error.
 - `fs.writeStream` can emit `'error'` *after* `finish`. Is this properly propagated?
 - Not sure whether I have any missed resource leaks? i.e. is the file descriptor inside the  `fs.writeStream` always properly closed?

Any comments or suggestions?

**Comment by vqvu** [comment]
> `{ position }` updates

If you just need it to be periodic, implement some sort of timer that checks `bytesWritten` and add it as one of the streams you're merging. Maybe

```javascript
var ended = false;
fileStream.once('close', () => ended = true);
_((push, next) => {
    push(null, { position: fileStream.bytesWritten });
    if (ended) {
        push(null, _.nil);
    } else {
        // For simplicity, this can take up to 100ms to detect that the write has finished.
        // You can do something more complicated to make the `close` handler
        // directly call `push(null, _nil)` and cancel the `setTimeout`.
        setTimeout(next, 100); // Or however long you want.
    }
});
```

> and final position

If you don't need it to be in the same status object as the `md5`, the above works. If you do, implement a custom transform (probably via `consume`) after the `merge` that forwards all of the `{ position }`, but holds back the `{ md5 }` until it detects the end of stream. Then `push` an object with both the final position and the md5.

> `req.on('close')` should be an error.

You'd need to implement this manually. using the`onFinish` handler. I don't know what the current `onFinished` does, but you'll need to put it there. Alternatively, you can probably create a stream that emits an error on `close` and a `nil` on `end`. Though this is a bit tricky to do. You can't just call `req.once('error')` in the generator function since that only gets called lazily, and there's no way to emit an error outside of the generator right now.

> `fs.writeStream` can emit `'error'` *after* `finish`. Is this properly propagated?

`through` only works with Duplex streams. Does `fs.writeStream` even implement `pipe`? And if so, can it emit `error` after the `pipe` finishes? If the answer is yes, then the error won't be propagated.

I don't know how you would properly detect the case where there is no error if errors can be thrown *after* `finish` though. You'd need something to tell you, "there won't be any more errors now".

> is the file descriptor inside the `fs.writeStream` always properly closed?

`through` uses `pipe`, so If `req.pipe(fs.createStream)` works, then you're probably fine. Otherwise, you'll probably need to manually `destroy` the fs stream.

**Comment by ronag** [comment]
> I don't know how you would properly detect the case where there is no error if errors can be thrown after finish though. You'd need something to tell you, "there won't be any more errors now".

`fs.writeStream` always emits `close` if `{ autoClose: true }`.

**Comment by vqvu** [comment]
Ah, ok. The rest of my comment still applies though.

**Comment by ronag** [comment]
Thanks!
