### ISSUE TITLE
race condition with .map(), .mergeWithLimit() and the end event

### ISSUE THREAD

**Issue by amit777** [caolan/highland#550]
I have a test suite running that occasionally fails with "Error: Cannot write to stream after nil".

It seems like one of the .map() calls is trying to run the callBack after the 'end' event is already reached.  

Is my understanding correct that the 'end' event should wait for all the stream events to get processed with .map()?  I'm trying to see if my expectation is not correct.

**Comment by amit777** [comment]
here is a little pseudo code:

```
groupstream.map(_.wrapCallback(_readgroup))
.mergeWithLimit(5)
.pipe(retstream);


var _readgroup = function(group, cb){
...
cb(null, {response})
}
```

The error is thrown when cb is called on a stream with nil already pushed.

**Comment by vqvu** [comment]
> Is my understanding correct that the 'end' event should wait for all the stream events to get processed with .map()?

Are you talking about the `end` event from `retstream`? If so, then yes, `pipe` should not call `retstream.end()` until after all the maps are completed.

Do you have a stack trace. I'd like to know what the caller of `push` is, since it's the caller's responsibility to make sure that `push(null, value)` is not called after `push(null, _.nil)`.

Also, what would help is a test case that I can run (it doesn't have to fail all the time, just once in a while). It's difficult to figure out what's going on here without one.

**Comment by amit777** [comment]
I think I mean the 'end' event from groupstream. (However, now your question has given me an idea). I'm a little tired now, and I think i've confused myself.  Here is the stack trace I occasionally get..
```
Error: Cannot write to stream after nil
    at Stream.write (/opt/app/node_modules/highland/lib/index.js:1531:15)
    at /opt/app/node_modules/highland/lib/index.js:612:33
    at Stream.s._send (/opt/app/node_modules/highland/lib/index.js:1448:9)
    at Stream.write (/opt/app/node_modules/highland/lib/index.js:1548:18)
    at Stream._send (/opt/app/node_modules/highland/lib/index.js:912:26)
    at Stream.write (/opt/app/node_modules/highland/lib/index.js:1548:18)
    at /opt/app/node_modules/highland/lib/index.js:652:15
    at /opt/app/node_modules/highland/lib/index.js:4012:21
    at /opt/app/node_modules/highland/lib/index.js:1491:9
    at Stream.s._send (/opt/app/node_modules/highland/lib/index.js:1448:9)
    at Stream.write (/opt/app/node_modules/highland/lib/index.js:1548:18)
    at Stream._send (/opt/app/node_modules/highland/lib/index.js:912:26)
    at Stream.write (/opt/app/node_modules/highland/lib/index.js:1548:18)
    at /opt/app/node_modules/highland/lib/index.js:652:15
    at cb (/opt/app/node_modules/highland/lib/index.js:4621:21)
    at /opt/app/models/domain.js:1283:11
    at next (native)
    at onFulfilled (/opt/app/node_modules/co/index.js:65:19)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7) - {}
```

**Comment by vqvu** [comment]
You're piping to a Highland stream from a Highland stream? Usually you don't need to do that.

Are you piping to the same stream from multiple places?

**Comment by amit777** [comment]
Yes, pipeing from a highland stream to another one.

And yes, i'm piping multiple streams to the same place.. I think that may because the 'end' event to come twice?

**Comment by amit777** [comment]
rather than using pipe, i've moved to using .each() to do retstream.write().. and then .on('end') to do some custom end logic.. this seems to be working for me now.  though I do appreciate any insights you have on my previous method above.

**Comment by vqvu** [comment]
Yes, piping from multiple sources will cause `end` events to be emitted multiple times. You're probably not seeing the error all the time because `Highland.prototype.end`is a bit more lenient than `Highland.prototype.write`. It allows `end()` to be called multiple time after the first one. It's only a `write` after an `end` that causes issues.

There are two ways to get around this:

The recommended way is to collect all of your source streams and do a `merge` on them. So rather than code that looks like this

```javascript
function pipeFromStreamA(retstream) {
    createStreamA().pipe(retstream);
}

function pipeFromStreamB(retstream) {
    createStreamB().pipe(retstream);
}

const retstream = _();
pipeFromStreamA(retstream);
pipeFromStreamB(retstream);
```

you would do

```javascript
const retstream = _([createStreamA(), createStreamB()])
    .merge();
```

If the above is not possible for whatever reason, you can `pipe` without emitting `end`.

```javascript
function pipeFromStreamA(retstream) {
    createStreamA().pipe(retstream, {end: false});
}

function pipeFromStreamB(retstream) {
    createStreamB().pipe(retstream, {end: false});
}

const retstream = _();
pipeFromStreamA(retstream);
pipeFromStreamB(retstream);

// Do custom end logic somehow.
```

Using `pipe` rather than `each` has the advantage of preserving backpressure.

But again, this approach is not recommended when you are only working with Highland streams. Using `merge` is much cleaner. `pipe` is mostly meant for interop with Node Writables.

**Comment by amit777** [comment]
Thank you! very helpful.  Also, one more question.. Is there a reason to use .on('data'...) vs .each() ?

**Comment by vqvu** [comment]
Always use `each`. I'm not sure if there's any reason at this point to use `on('data')` or `on('error')` or `on('end')` at all. I certainly never have. The events kind of lie outside of the core stream framework, so we don't recommend that you use them. It's why we don't (afaik) document them on the website.

Maybe you might need to in weird interoperability cases, but usually that's better done by converting to a Node stream instead. Like so:

```javascript
// May need to pass {objectMode: true} depending on the contents of the stream.
const nodeStream = new stream.Passthrough();

highlandStream.errors(err => nodeStream.emit('error', err)
    .pipe(nodeStream);

// Use `on('data')` and friends on the node stream.
```

I'm going to close this issue since it seems like you no longer see the error. Feel free to reopen if you run into the same error again.
