### ISSUE TITLE
Debounce on a finite stream: unexpected behavior

### ISSUE THREAD

**Issue by pavel** [caolan/highland#553]
There's unexpected behavior, when `debounce` is used on a finite stream.

Consider the following example:
``` javascript
var _ = require("highland");

_([1])
    .tap(function () { console.time("operation"); })
    .debounce(100)
    .tap(function () { console.timeEnd("operation"); })
    .resume();
```
Output shows that the measured time for the label "operation" is less than 100ms. The thing is that `debounce` calls `next` after the first value `1`, and during the next spin of `debounce` the `nil` arrives, which makes `debounce` stop the timeout it started when the value `1` has arrived.

Please, let me know what you think about this behavior.

**Comment by vqvu** [comment]
This seems fine to me. The `nil` value guarantees that there will be no
more data, so there's no reason to wait. Is there a use case where you need
it to always wait the full timeout regardless?

**Comment by pavel** [comment]
For me this arose when I tried to use `debounce` as a delay mechanism. 

Maybe to avoid future misunderstanding you could've to add this:
> The `nil` value guarantees that there will be no more data, so there's no reason to wait.

as a note in documentation.

**Comment by pavel** [comment]
I consider to be misleading this part of the docs, which states:
> **Holds off** pushing data events downstream **until there has been no more data for ms milliseconds**

So when `nil` comes in this means `no more data` but without **for ms milliseconds**, as `debounce` releases data immediately.

**Comment by vqvu** [comment]
Ah, I see what you mean. I agree that the docs can be interpreted as you
say. I don't mind changing the implementation to wait even when it gets a
`nil`.

Do you have a specific use case that you can share where the current
behavior is bad/wrong/annoying? I like to learn more about how people are
using Highland to see which behavior is or isn't important, especially for
edge cases like this.

**Comment by vqvu** [comment]
> Do you have a specific use case that you can share where the current behavior is bad/wrong/annoying?

Nevermind. I didn't see your previous comment describing your use case.

**Comment by pavel** [comment]
I wound't rush changing this implementation. I think that there's a difference between "immediate" and "continuous" streams, which is the root cause of this kind of situations. This difference needs to be established before changing `debounce`.

**Comment by vqvu** [comment]
I would say the difference is between finite and infinite streams. `debounce` wasn't meant for finite streams and you'll get this early termination behavior for all finite streams regardless of their data source (immediate or not).

IMO, both behavior (current and proposed) can be the correct behavior for a thing that people would call the `debounce` transform. I don't have strong feelings either way, though the proposed behavior does have the nicer guarantee that the time between any two emitted elements is at least the debounce timeout.

Can you elaborate on what you mean when you say "This difference needs to be established before changing `debounce`."? Do you just mean the docs should mention what it does in this special case? If so, I agree.

Perhaps the problem here is that you're using `debounce` to delay an element rather than something more direct like this

```javascript
function delay(ms) {
	return function (stream) {
		return stream.consume((err, x, push, next) => setTimeout(() => {
			push(err, x);
			if (x !== _.nil) {
				next();
			}
		}, ms))
	};
};

_([1])
    .tap(function () { console.time("operation"); })
    .through(delay(100))
    .tap(function () { console.timeEnd("operation"); })
    .resume();
// => operation: 103.757ms
```

**Comment by pavel** [comment]
> This difference needs to be established before changing debounce.

Documentation should reflect handling of this special case.

Also I agree that using `debounce` as a delay mechanism is wrong. Your `delay` function is exactly what should be used.
