### ISSUE TITLE
Forks and data corruption

### ISSUE THREAD

**Issue by jbergknoff** [caolan/highland#555]
I recently had data corruption which I traced to the fact that, when a Highland stream is forked, all consumers are sent the exact same `Buffer`. I was passing the forked streams through a transform which was modifying the `Buffer`; one fork would modify the data and the other fork would receive (from Highland) the now-corrupt data (related: https://github.com/mafintosh/csv-parser/pull/60).

Is this something that should be addressed within Highland? Highland can clone the `Buffer` once per consumer (+per observer) and send out those copies, though I guess this will inflate memory usage. IMO it's bad form for a fork consumer to directly modify the passed `Buffer`, but arguably Highland should still offer some guarantee that all forks receive the same data.

Demonstration:

```js
'use strict';
const highland = require('highland');

const input = highland([new Buffer(':)')]);
const fork1 = input.fork();
const fork2 = input.fork();

fork1.each(
  (x) => {
    console.log('fork 1:', x.toString());
    x[1] = '('.charCodeAt(0);
  }
);

fork2.each(
  (x) => {
    console.log('fork 2:', x.toString());
  }
);
```

Output:

```
fork 1: :)
fork 2: :(
```

Although this example uses a `Buffer` explicitly passed into a Highland constructor, the situation is the same when we are forking a "real" stream, like a download.

**Comment by vqvu** [comment]
I'm -1 on this. Highland should not be in the business of sniffing its value types and applying special logic to certain cases. It gets hairy fast. If we do it for `Buffer`, then people will want us to do it for arrays or any number of mutable types. And that's not getting into cases like nested data (what if you're passing around a `{foo: new Buffer()}` rather than a `Buffer`) or memory usage (people not modifying their Buffers should not have to pay for the allocations).

Highland offers the guarantee that all forks receive the same *value*. It does not (and in the general case cannot) guarantee that the contents and behavior of said value will not change as the forks execute.

If you need to clone the data, you should do it immediately after the `fork()`

```javascript
...
const fork1 = input.fork().map(Buffer.from);
const fork2 = input.fork().map(Buffer.from);
...
```

 or before you modify.

**Comment by jbergknoff** [comment]
Thanks for the quick response. You make several good points as to why this should not be Highland's responsibility, and I have to agree with you.

Nevertheless, the behavior I described is surprising, particularly when one is forking a readable stream. There's an expectation that that data would be immutable, inert; obviously it's not necessarily the case, and I agree that it's not on Highland to solve that. Maybe this warrants mentioning on the documentation for `fork`.
