### ISSUE TITLE
Early Returns with Pipe?

### ISSUE THREAD

**Issue by jayzawrotny** [caolan/highland#559]
Hello I have some experience with node streams but am completely new to Highland.js and reactive programming.

What I have setup is something like:

```js
function indexRoute (err, req, res, next) {
  return _([ req.body.targetBranch ])
    .pipe(createBuildState())
    .pipe(buildAssets())
    .map(JSON.stringify)
    .pipe(res);
}

function createBuildState () {
  return _()
    .flatMap((targetBranch) => {
       return _([
         getLastBuildFromDB(targetBranch),
         getNewestAssetVersion(targetBranch),
       ])
       .parallel(2)
       .append(targetBranch)
       .collect();
    })
    .map(([lastBuild, assetVersion, targetBranch]) => {
        return new Immutable.Map({
          lastBuild,
          assetVersion,
          targetBranch,
        });
    })
}
```

What I expect is that createdBuildState() returns a Highland stream that recieves the target branch value, that gets flat mapped to an array of initial data, and then mapped to an immutable model before getting to buildAssets() stream or JSON.stringify map. What seems to be happening is that JSON.stringify is being called with the original branchTarget string as if createBuildState stream or similarily created buildAssets functions was not called at all.

Is there something I'm missing?

**Comment by vqvu** [comment]
The reason why this doesn't work is because highland streams aren't automatically pipelined. In your example, the result of `_()` is a stream, the result of `.flatMap` is a *different* stream, and the result of `.map` is yet another streams. Only the original `_()` stream can be piped to. If you try to `pipe` to the `.map` stream (like you've done here), it will look as if all of the other stages never happened (including the `.map` stage).

In Highland, `pipe` is only really useful for piping out to a node writable. It should not be used in the middle of a pipeline. Instead, use [through](http://highlandjs.org/#through) if you want to implement these kinds of reusable transforms.

```javascript
function indexRoute (err, req, res, next) {
  return _([ req.body.targetBranch ])
    .through(createBuildState) // Through will pass the current stream to createBuildState.
    .through(buildAssets)
    .map(JSON.stringify)
    .pipe(res); // Assuming res is a Node Writable.
}

function createBuildState (source) {
  return source
    .flatMap(targetBranch => ...)
    .map(([lastBuild, assetVersion, targetBranch]) => ...);
}
```

**Comment by jayzawrotny** [comment]
Oh I see thanks for clarifying. If it means anything I did read that `through` is preferred in the docs but was thrown off by this:

> Pipes a Highland Stream to a Node Writable Stream (Highland Streams are also Node Writable Streams)

Which made me think it was just recommended to use through to not have to create new highland stream instances.

**Comment by vqvu** [comment]
Yep. I'm going to remove that wording. It's misleading.
