### ISSUE TITLE
Fork confusion

### ISSUE THREAD

**Issue by jayzawrotny** [caolan/highland#561]
Hello again. I found myself uncertain about how the `fork` method works from the documentation. Specifically:

> **Forks a stream**, allowing you to add additional consumers with shared back-pressure. A stream forked to multiple consumers will only pull values from its source as fast as the slowest consumer can handle them.

What does `Forks a stream` mean exactly? If I call `fork`, is the result a new branch? What happens to the previous stream?

My use case is a small JS build server triggered by a POST request. We don't want to wait for the build to finish before responding, we just want to do some lookups to see if a build is required, and what type of build action it is then respond with the course of action it's going to take.

I've setup a pipeline from the request to the response managing a model representing the state & future behavior of the build process. The `fork` method is required in the last step to send the build state down the pipline to the response while also sending it to the build pipeline.

Below is my best attempt at applying it:

```js
function forkBuildStream (stateStream) {
  let buildStream = stateStream.fork();

  buildStream
    .observe()
    .tap(slack('start_build'))
    .through(runBuildAction)
    .tap(slack('end_build'));

  return stateStream.resume();
}

function startBuildProcess (stateStream) {
  return stateStream
    .filter(isBuildActionRequired)
    .map(updateBuildState);
    .through(forkBuildStream)
}

module.exports = startBuildProcess;
```

A hopefully helpful visualization of the intended flow:

```                        
                  .filter --s--------------------- (state model coming down)
   .map(updateBuildState) --s?-------------------- (stream might get data passed to it)
-+------ .original stream --s--------------------- (.through(forkBuildStream))
    |  .map(formatToJson) --s---------------------
    |     .pipe(response) --j--------------------- (original stream ends here)
    +-- .fork().observe() --s--------------------- (gets the same state passed to formatter)
    .flatMap(buildAssets) --b--------------------- (creates build stream)
   .flatMap(uploadAssets) -----u------------------ (uploads to S3 or wherever)
        .tap(sendToSlack) --------s--------------- (posts update to slack channel)      
```

**Comment by vqvu** [comment]
Fork does stream multiplexing. It takes a stream and can turn it into multiple identical ones. In that sense, it's like `observe`. The difference is that all forks share backpressure while observers don't exert backpressure at at. Typically you either `fork` or you `observe`, never both. It also renders the old stream useless, while`observe` doesn't, so you need to call `fork` at least two times.

Usually, forking looks something like this:

```javascript
const someStream = ...

const forkA = someStream.fork();
const forkB = someStream.fork();

forkA.through(aTransform)
  .pipe(somewhere);
  
forkB.through(anotherTransform)
  .each(doSomething);
```

The forks will wait on each other and execute in lock-step (see below for an example).

That said, you probably want to use `observe` in this case rather than `fork`. You want to return a response as soon as possible, so you will not want the stream writing the response to share backpressure with the stream doing the build pipeline. Shared backpressure means all streams will only execute as fast as the *slowest* stream. With `observe`, the observers are passive, so they will execute no faster than the main stream, but the main stream can execute as fast as it wants.

Here, the build stream will wait on the response writing stream. This isn't a problem if building is slower than sending the response.

```javascript
const stateStream = ...

// Always set up the observers first. If you do them last, you risk a race condition if the
// main stream is really fast.
stateStream.observe()
  .through(buildAssetsAndPostToSlackWhenDone);

// The main stream just writes the response.
stateStream.map(formatToJson)
  .pipe(response);
```

If you want, you can go further. Here, both are decoupled from each other. No backpressure exists, and the two streams will execute independently of each other.

```javascript
const stateStream = ...

stateStream.observe()
  .through(buildAssetsAndPostToSlackWhenDone);

stateStream.observe()
  .map(formatToJson)
  .pipe(response);

// Consumes the stateStream. This will cause it to feed the observers data as it goes.
stateStream.resume();
```

----

P.S. Here's some code that demonstrates the difference between the two. Execute either `fork` or `observe`.

```javascript
// Simulates work.
function delay(x, ms) {
  return _((push, next) => setTimeout(() => {
    push(null, x);
    push(null, _.nil);
  }, ms));
}

function fork() {
  console.log('====== FORK ======');
  const now = Date.now();

  const stream = _([1, 2, 3])
    .tap(x => console.log(`original ${x}: ${Date.now() - now}`));

  const forkA = stream.fork();
  const forkB = stream.fork();

  forkA.flatMap(x => delay(x, 25))
    .each(x => console.log(`forkA    ${x}: ${Date.now() - now}`));


  forkB.flatMap(x => delay(x, 100))
    .each(x => console.log(`forkB    ${x}: ${Date.now() - now}`));
}

function observe() {
  console.log('====== OBSERVE ======');
  const now = Date.now();

  const stream = _([1, 2, 3]);

  const observerA = stream.observe();
  const observerB = stream.observe();

  observerA.flatMap(x => delay(x, 25))
    .each(x => console.log(`observerA  ${x}: ${Date.now() - now}`));


  observerB.flatMap(x => delay(x, 100))
    .each(x => console.log(`observerB  ${x}: ${Date.now() - now}`));

  // We need to consume the source stream for this to work.
  stream
    .each(x => console.log(`main       ${x}: ${Date.now() - now}`));
}
```

The results look like this

```
====== FORK ======
original 1: 6
forkA    1: 37
forkB    1: 109
original 2: 109
forkA    2: 136
forkB    2: 211
original 3: 211
forkA    3: 237
forkB    3: 311
```

and

```
====== OBSERVE ======
main       1: 5
main       2: 8
main       3: 8
observerA  1: 37
observerA  2: 63
observerA  3: 89
observerB  1: 111
observerB  2: 212
observerB  3: 313
```

Notice how the forks interleave with each other while the observers both have to wait on the main stream but not each other.

**Comment by jayzawrotny** [comment]
Wow thanks for such a very detailed & helpful response. It makes total sense now!

**Comment by gregory** [comment]
@vqvu feels like this should be somewhere in the doc, no?

**Comment by vqvu** [comment]
How much detail would you like? Is a link to my post OK?

It's hard for me tell what's confusing about the current doc, since I already know what `fork` does, and so "allowing you to add additional consumers with shared back-pressure" makes perfect sense to me.

**Comment by gregory** [comment]
I guess the link would work. I guess any example that highlight the difference between the two will help.
