### ISSUE TITLE
.resume not needed?

### ISSUE THREAD

**Issue by FsecureSamiTikka** [caolan/highland#578]
http://highlandjs.org/#fork seems to imply one needs to call .resume on a forked stream to make it work.

However, when I try this:
```
var hi = require('highland')
var numbers = hi([1, 2, 3, 4])
var even = numbers.fork().filter((n) => { return n % 2 == 0 })
var odd = numbers.fork().filter((n) => { return n % 2 == 1 })
even.resume()
odd.resume()
hi([even, odd]).merge().each(hi.log)
```
it prints nothing. If I remove the two lines that call resume, all the numbers are printed.

So, in reality, calling .resume for a forked stream is not needed and doesn't even work. Should the documentation be updated or have I misunderstood something?

**Comment by LewisJEllis** [comment]
This is expected behavior. The docs are just showing an example of how the shared backpressure works, not indicating that `.resume` is necessary; it's necessary to consume from all forks, and `.resume()` is one way to consume a stream. `.each` is also a way to consume a stream, as you're attempting to do here. Take a look at the section on [laziness](http://highlandjs.org/#laziness) which describes this more.

It's not that `.resume` isn't needed or doesn't work - you're just trying to consume the two forks using `.merge().each()` after they've already been consumed by `.resume()` and so you're not seeing anything logged. You can think of `.resume()` like `.each(()=>{})`. You could also try:
```javascript
var hi = require('highland')
var numbers = hi([1, 2, 3, 4])
var even = numbers.fork().filter((n) => { return n % 2 == 0 })
var odd = numbers.fork().filter((n) => { return n % 2 == 1 })
even.each(hi.log)
odd.each(hi.log)
```
and
```javascript
var hi = require('highland')
var numbers = hi([1, 2, 3, 4])
var even = numbers.fork().filter((n) => { return n % 2 == 0 })
var odd = numbers.fork().filter((n) => { return n % 2 == 1 })
even.each(hi.log)
odd.each(hi.log)
hi([even, odd]).merge().each(hi.log)
```
and
```javascript
var hi = require('highland')
var numbers = hi([1, 2, 3, 4])
var even = numbers.fork().filter((n) => { return n % 2 == 0 })
var odd = numbers.fork().filter((n) => { return n % 2 == 1 })
odd.resume()
even.each(hi.log)
odd.each(hi.log)
```
for some more examples of behavior.
