### ISSUE TITLE
Approach for using event emitters to push data downstream

### ISSUE THREAD

**Issue by dremekie** [caolan/highland#581]
I'm using a library (https://www.npmjs.com/package/saxpath) to read from an XML filestream and would like to send XML nodes downstream. It emits events that I use to push data downstream but it ends up overrunning its memory limit. I believe its doing this since it is simply pushing data downstream when it really should be "pulled" (basically, there is no back-pressure).

I do the following in a `consume` block

```
            const fileStream = fs.createReadStream(myLargeXML);
            const saxParser = sax.createStream(true);
            const streamer = new saxpath.SaXPath(saxParser, myXPath);

            fileStream.pipe(saxParser);

            streamer.on('match', (xml) => {
              push(xml);
            });

            saxParser.on('end', () => {
              push(null, h.nil);
            });
```

What is the correct approach to do this?

Thanks in advance

**Comment by vqvu** [comment]
Backpressure requires proper support from the source stream---you need some way to pause and resume the source. Skimming through the `saxpath` implementation, it looks like it's just a regular event emitter that doesn't support pausing.

The best way to get backpressure is to ask `saxpath` to expose a proper `objectMode` Readable stream. Highland supports these by default. Then you could do something like this, even outside of a `consume` block.

```javascript
const fileStream = fs.createReadStream(myLargeXML);
const saxParser = sax.createStream(true);
const streamer = new saxpath.SaXPath(saxParser, myXPath);

fileStream.pipe(saxParser);

const highlandStream = h(streamer);
```

Alternatively, a `pause`/`resume` mechanism would work. You'd then need to do something like this to manually deal with backpressure.

```javascript
const fileStream = fs.createReadStream(myLargeXML);
const saxParser = sax.createStream(true);
const streamer = new saxpath.SaXPath(saxParser, myXPath);
const firstTime = true;

const highlandStream = h((push, next) => {
  if (firstTime) {
    streamer.on('match', xml => {
      streamer.pause();
      push(null, xml);
      next();
    });
    streamer.on('end', () => push(null, h.nil));
    firstTime = false;
  }

  streamer.resume();
});
```

Unfortunately, these two solutions would likely require pause support from `sax-js`, which doesn't seem to exist according to its readme.

Outside of that, you may be able to apply backpressure at the `fileStream` level, which does support pause/resume. This is very much not recommended, however, since there can easily be unexpected data races that can cause deadlock. It wouldn't really be reliable unless you can guarantee that both `saxpath` and `sax` are synchronous. For that reason, I won't post any code here.

**Comment by dremekie** [comment]
Thanks. That makes sense.
