### ISSUE TITLE
Destroy method should throw an error if passed

### ISSUE THREAD

**Issue by Kefir100** [caolan/highland#685]
Hey. 
Awesome library, but I found some kind of a bug I guess. 
[Higland destroy method](http://highlandjs.org/#destroy) does not accept an error argument but the [native Node streams](https://nodejs.org/dist/latest-v12.x/docs/api/stream.html#stream_readable_destroy_error) do. 
I test my streams in a project and I want to destroy my stream with an error and check for it. 
Why is there no error argument and was it an intentional decision?

**Comment by vqvu** [comment]
Highland isn't meant to match the node stream interface. There are a lot of
incompatibilities between the two.

I can add the error argument, but first can you explain your use case? Why
do you need it?

**Comment by Kefir100** [comment]
I have got a package that uses highland streams and want to test out the case on a buggy stream that throws error when it is destroyed. Btw streams might be destroyed intentionally and it would be nice to have any data signaling the reason why it was destroyed.

**Comment by vqvu** [comment]
If you just want to test against a buggy stream, can you just construct a stream that throws an error?

```javascript
const buggyStream = _((push) => {
  setTimeout(() => push(new Error('asdfasdf')), 1000);
});
```

The reason I ask is because I don't know of a good reason to destroy a stream out-of-band like this. As implemented, observers and consumers may not even see the `nil` token if the stream is currently paused (this behavior is documented: `This function calls end() on the stream and unlinks it from any piped-to streams.`). If you destroy a stream before it's consumed, the consumer deadlocks, since no events will be emitted. It's not a great feature, and I don't want to encourage using `destroy` to stop a stream out of band.

I would much prefer to find a way to stop the stream within the regular consumption and emission framework (i.e., via usage of `pull`, `consume`, or existing operators).

**Comment by Kefir100** [comment]
Good point, that helps. Lets close the issue then 👍
