### ISSUE TITLE
Is this project semi-abandoned?

### ISSUE THREAD

**Issue by Mautriz** [caolan/highland#701]
Was looking for a stream wrapper to read and modify files, this one looked the most promising

Last commit 10 months ago, 3.0 rewrite started in 2014 and still not ready, is this abandoned or am I missing something?

**Comment by eccentric-j** [comment]
Currently, it is not maintained and is not under active development. However, it is very stable and is still my goto for streams in node js after first using it in 2015. I have been stepping in to help people with issues for the past month or so.

Some libraries become abandoned due to becoming obsolete, some due for political reasons, Highland falls into a different category where it's essentially "complete". It solves the core problem well, continues to work with the latest versions of node, and has no critical issues yet to be fixed. Version 3 was more like cake icing with a more organized codebase and some added methods for convenience. 

If you choose to use this library, I'll do my best to help with any issues.

**Comment by eccentric-j** [comment]
As for working with files, I really love combining gulp + highland. For example:

With a package.json like:

```json
{
  "dependencies": {
    "gulp": "^4.0.2"
  }
}
```

and a `gulpfile.js` like:

```js
const stream = require("highland");
const gulp = require("gulp");

function copy () {
  return gulp.src("a/*.txt", { encoding: "utf8"})
    .pipe(stream())
    .tap(vinylFile => console.log({
      path: vinylFile.path,
      relative: vinylFile.relative,
      contents: vinylFile.contents.toString("utf8"),
    }))
    .pipe(gulp.dest("b"));
}

exports.copy = copy;
```

You can run `gulp copy` from anywhere within that project folder to copy all text files from folder `a` to folder `b`. With highland you get the ability to filter, map, reduce, flatMap, etc... to easily control the pipeline without extra gulp plugins. Gulp provides a solid CLI experience, handles the IO pretty cleanly, and has a giant ecosystem of plugins for everything like uploading to S3, to transpiling the latest ES, to generating sprite sheets from a pile of SVGs.
